name: Build GodMode9

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install devkitPro
        run: |
          wget https://github.com/devkitPro/pacman/releases/latest/download/devkitpro-pacman.deb
          sudo apt install -y ./devkitpro-pacman.deb
          sudo dkp-pacman -Syu --noconfirm
          sudo dkp-pacman -S --noconfirm 3ds-dev

      - name: Install firmtool
        run: |
          sudo apt install -y python3-pip
          pip3 install firmtool

      - name: Build firm
        run: |
          source /etc/profile.d/devkit-env.sh
          make firm

      - name: Upload GodMode9.firm
        uses: actions/upload-artifact@v4
        with:
          name: GodMode9-modified
          path: output/GodMode9.firm